spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create


  datasource:
    url: jdbc:mysql://localhost:3306/expert
    username: root
    password: 2232
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
